### PR TITLE
Explorers page

### PR DESCRIPTION
**Pull request by phelixbtc**

### CODE REVIEW

**Comment by phelixbtc** [comment]
http://beta.namecoin.org/?p=explorers

**Comment by JeremyRand** [comment]
There is at least one other explorer with name support, I'm looking for a link now.

**Comment by JeremyRand** [comment]
http://namecoin.webbtc.com/

It's open-source, unlike namecha.in, but doesn't support HTTPS (while namecha.in does).

**Comment by phelixbtc** [comment]
Added. About to merge.

**Comment by JeremyRand** [comment]
https://bkchain.org/nmc is showing "Backend server connection error" for me.  Is that a temporary glitch?

**Comment by phelixbtc** [comment]
Hmm. It did not say so a couple of days ago. The page for BTC says the same so I assume they will repair it.

**Pull request merged**
