### PR TITLE
remove dead websites added new exchanges

### PR DESCRIPTION
**Pull request by tosh0**

### CODE REVIEW

**Comment by phelix** [comment]
ACK

**Comment by JeremyRand** [comment]
ACK, except that I can't verify that Cex.io actually does Namecoin.  There appears to be a Namecoin logo on their site, but I don't see the market listed anywhere.  Is an account needed to see that market?

**Comment by tosh0** [comment]
it does namecoin / btc since more than a year ago.

**Comment by phelixbtc** [comment]
@tosh0 Maybe the cex.io link is broken?  https://cex.io/nmc-btc seems to work.

**Comment by tosh0** [comment]
@phelix  You are right, I just changed to that.

**Pull request merged**
