### PR TITLE
OpenSSL Consensus Bug has been fixed.

### PR DESCRIPTION
**Pull request by JeremyRand**
Would be great to get this merged within 24 hours, since I will be sending the namecoin.org URL to some people and don't want to scare them.

### CODE REVIEW

**Comment by phelixbtc** [comment]
Should we mention that users are still on SPV?

**Comment by JeremyRand** [comment]
Sure, I'll add that.

**Comment by JeremyRand** [comment]
@phelixbtc How's this?

**Comment by phelixbtc** [comment]
ACK

**Comment by JeremyRand** [comment]
Thanks, merging.

**Pull request merged**
