### PR TITLE
home: change in text forum link to active topics

### PR DESCRIPTION
**Pull request by phelix**

### CODE REVIEW

**Comment by JeremyRand** [comment]
I don't follow how this is an improvement.  When I click a forum link, I expect to be sent to the forum index, not a search page.

**Comment by phelixbtc** [comment]
The page says "join us on the forum". Thus it is more suitable to go to the active topics and display what is currently going on. It gives a more lively image of the forum. The menu link still goes to the forum index btw.

**Comment by JeremyRand** [comment]
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA256

@phelixbtc I believe such a link would confuse me if I clicked it.
It's not hard to look at the "last post" dates in the various
subforums on the index page if looking for recent posts.  Many users
are more interested in finding content that is relevant to their
interests (even if a few months old), rather than prioritizing
recentness above all else.
-----BEGIN PGP SIGNATURE-----
Version: GnuPG v2

iQIcBAEBCAAGBQJWn1cLAAoJEAHN/EbZ1y06i+cP/1IaOPI/veN47QQPMVpXGZB7
VviFS9MGhHxuHwvmXXYT7CF7XF+vY28TXAYJ8tR1EdqpIc67Zk9tDDD7sUD9iLhY
oHXYkKbMXWPBwvvRdpOYkj96ViNE5T+VMxC8iTkFLrV78xalFcKunmnX97Ljzj5y
Rztewa4qtfVj3fEdvM/PRDcow2BYwyhISJNYH1NTfbOR/qWS2lwa9Wttpro8v+Mc
7HaoTUhygbRbMjABtAc/QiuKfPlbn9hsI0uPVRM2sM7YlxHHheio/bmIHnT25v50
6lzi13nq80qPvwigqHofD4xkEzRHHQOP7ZVSzv+hPAq4Zcx29eQKk0d/hZlNgFEA
7O5TUObrF4Hnomcr1LX+MjTpyA5djrUGTFyf2u56ZrYxyVEAx2jCTSQW1rqgXkNZ
uv4KNilIGiV7I2Zn29c3Utq42S/gAzeIMXS4FNZEOs5q/ObKcvEjMErTqmeVAkIH
A2peShAaMxdQWxN4dtlHWykNGKBPJ9UNnPgbSlwoTtKzjtW2XAlI6J/ZCXRMZKTV
cizXxLUL8L8BRtckTuj5hEBfhlPByN1FRjLN1hQy0G3LnxhZUyKatkihD6lRQHfK
JXMSOk7E7VBxD2DbB3ARMv81c1P1i+JMOA4SppxiBud69rsPOK0yml7UOgG98g8v
KFCV1IjJQ3UBJXV6MMkL
=y1ud
-----END PGP SIGNATURE-----

**Comment by phelixbtc** [comment]
@JeremyRand Most people are not confused so easily, yet casual visitors don't have time to check all the subforum last post dates.  

Anyone else with an opinion?

**Comment by phelixbtc** [comment]
@JeremyRand I am convinced of this change and I think it is not important enough to justify a big discussion. If you differ and have a strong opinion please ask others to comment on Github or on the forum.

**Comment by JeremyRand** [comment]
@phelixbtc I am displeased that you merged this despite my objections when no one else had weighed in.  This patch violates the principle of least surprise.  It also takes me about 5-10 seconds to look at the post dates for the subforums; I cannot imagine any visitor who would be inconvenienced by this.  Please revert this change, and please do not merge things under such circumstances again.

**Comment by JeremyRand** [comment]
Change has been reverted.  Please do not merge things under such circumstances again.

**Pull request merged**
